name: Install vbuild
description: Install the vbuild tool

runs:
  using: composite
  steps:
    - name: Install vbuild
      shell: bash
      run: |
        set -e
        curl \
          --location \
          'https://github.com/Eeems/vbuild/releases/download/0.0.18/vbuild-vbuild-ubuntu' \
          --output /usr/local/bin/vbuild
        chmod +x /usr/local/bin/vbuild
